DROP PROCEDURE IF EXISTS PA_DEVU_LOGIN;
DELIMITER $$
CREATE OR REPLACE PROCEDURE PA_DEVU_LOGIN(
    IN  P_LOGIN VARCHAR(11), 
    IN  P_PASS VARCHAR(20), 
    OUT P_CODI_RESP INT(5),
    OUT P_DESC_RESP VARCHAR(50))
BEGIN
    DECLARE V_LOGIN VARCHAR(20) DEFAULT NULL;
    DECLARE V_PASS VARCHAR(50) DEFAULT NULL;
    DECLARE V_PASS1 VARCHAR(50) DEFAULT NULL;
    DECLARE V_CODI INT(10) DEFAULT NULL;

    SELECT USER_LOGI, USER_PASS, USER_CODI 
    INTO V_LOGIN, V_PASS, V_CODI
    FROM HIDRO_USER 
    WHERE TRIM(UPPER(USER_LOGI)) = TRIM(UPPER(P_LOGIN));

    IF V_LOGIN IS NOT NULL THEN
	SELECT SHA(TRIM(P_PASS)) INTO V_PASS1;
      IF V_PASS = V_PASS1 THEN
        SET P_CODI_RESP = 1;
	SET P_DESC_RESP = 'Datos correctos';

	SELECT USER_CODI, 
	IFNULL(USER_DESC, PERS_NAME||' '||PERS_LAST) USER_DESC, 
	INVE_CODI,
	INVE_NAME,
	MODU_CODI,
	MODU_DESC
	FROM HIDRO_USER U, 
	     HIDRO_PERS P,
	     HIDRO_INVE I,
	     HIDRO_MODU M, 
	     HIDRO_INVE_MODU IM
	WHERE U.USER_PERS_CODI = P.PERS_CODI
	AND   I.INVE_USER_CODI = U.USER_CODI
	AND   I.INVE_CODI = IM.INMO_INVE_CODI
	AND   M.MODU_CODI = IM.INMO_MODU_CODI
        AND USER_CODI = V_CODI;
      ELSE
	SET P_CODI_RESP = 2;
	SET P_DESC_RESP = 'Datos incorrectos';
      END IF;
    ELSE
        SET P_CODI_RESP = 2;
	SET P_DESC_RESP = 'Datos incorrectos';
    END IF;

END$$


------------------------------------------------

CALL PA_DEVU_LOGIN('RPORTILLO','12345678', @CODI_RESP, @DESC_RESP);

SELECT @CODI_RESP CODI, @DESC_RESP RESP;
