INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Concepcion');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('San Pedro');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Cordillera');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Guaira');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Caaguazu');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Caazapa');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Itapua');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Misiones');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Paraguari');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Alto Parana');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Central');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Ñeembucu');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Amambay');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Canindeyu');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Presidente Hayes');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Alto Paraguay');
INSERT INTO HIDRO_DEPT (DEPT_DESC)
VALUES ('Boqueron');

INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Emboscada',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Altos',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Arroyos y Esteros',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Atyra',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Caacupe',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Caraguatay',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Eusebio Ayala',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Isla Pucu',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Itacurubi de la cordillera',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Juan de Mena',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Loma Grande',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Mbocayaty del Yhaguy',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Nueva Colombia',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Piribebuy',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Primero de Marzo',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('San Bernardino',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('San Jose Obrero',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Santa Elena',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Tabati',3);
INSERT INTO HIDRO_CIUD(CIUD_DESC,CIUD_DEPT_CODI)
VALUES('Valenzuela',3);

INSERT INTO HIDRO_USER_ROLE(ROLE_DESC)
VALUES('Administrador');
INSERT INTO HIDRO_USER_ROLE(ROLE_DESC)
VALUES('SuperUser');
INSERT INTO HIDRO_USER_ROLE(ROLE_DESC)
VALUES('Audit');


INSERT INTO HIDRO_PERS(PERS_CEDU,PERS_NAME,PERS_LAST,PERS_TELE,PERS_DIRE,PERS_USER_REGI,PERS_USER_MODI)
VALUES('4133266','Derlis','Caballero','0981186744','Loma Pyta','dcaballe','dcaballe');
INSERT INTO HIDRO_PERS(PERS_CEDU,PERS_NAME,PERS_LAST,PERS_TELE,PERS_DIRE,PERS_USER_REGI,PERS_USER_MODI)
VALUES('4509174','Esteban David','Acevedo Talavera','0981402035','Emboscada','dcaballe','eacevedo');


INSERT INTO HIDRO_USER(USER_DESC,USER_LOGI,USER_PASS,USER_ESTA,USER_REGI,USER_MODI,USER_PERS_CODI,USER_ROLE_CODI)
VALUES('Derlis Caballero Mendoza','dcaballe','1234','A','dcaballe','dcaballe',1,1);
INSERT INTO HIDRO_USER(USER_DESC,USER_LOGI,USER_PASS,USER_ESTA,USER_REGI,USER_MODI,USER_PERS_CODI,USER_ROLE_CODI)
VALUES('Esteban David Acevedo Talavera','eacevedo','4321','A','dcaballe','dcaballe',2,2);


INSERT INTO HIDRO_INVE(INVE_NAME,INVE_LATI,INVE_LONG,INVE_USER_REGI,INVE_USER_MODI,INVE_USER_CODI,INVE_CIUD_CODI)
VALUES('Inv Lechuga','0000','1111','dcaballe','dcaballe',1,1);


INSERT INTO HIDRO_MODU(MODU_DESC)
VALUES('AGUA');
INSERT INTO HIDRO_MODU(MODU_DESC)
VALUES('CLIMA');
INSERT INTO HIDRO_MODU(MODU_DESC)
VALUES('ACTUADOR');
INSERT INTO HIDRO_MODU(MODU_DESC)
VALUES('MEDIDOR');
INSERT INTO HIDRO_MODU(MODU_DESC)
VALUES('LUZ');

INSERT INTO HIDRO_INVE_MODU(INMO_INVE_CODI,INMO_MODU_CODI)
VALUES(1,1);
INSERT INTO HIDRO_INVE_MODU(INMO_INVE_CODI,INMO_MODU_CODI)
VALUES(1,2);
INSERT INTO HIDRO_INVE_MODU(INMO_INVE_CODI,INMO_MODU_CODI)
VALUES(1,3);
INSERT INTO HIDRO_INVE_MODU(INMO_INVE_CODI,INMO_MODU_CODI)
VALUES(1,4);
INSERT INTO HIDRO_INVE_MODU(INMO_INVE_CODI,INMO_MODU_CODI)
VALUES(1,5);

INSERT INTO HIDRO_UNID_MEDI(MEDI_DESC,MEDI_DESC_ABRE)
VALUES('Centigrados','C');
INSERT INTO HIDRO_UNID_MEDI(MEDI_DESC,MEDI_DESC_ABRE)
VALUES('Humedad','DH');
INSERT INTO HIDRO_UNID_MEDI(MEDI_DESC,MEDI_DESC_ABRE)
VALUES('Ambiente','DT');
INSERT INTO HIDRO_UNID_MEDI(MEDI_DESC,MEDI_DESC_ABRE)
VALUES('Ninguno','N');
INSERT INTO HIDRO_UNID_MEDI(MEDI_DESC,MEDI_DESC_ABRE)
VALUES('Litros','L');
INSERT INTO HIDRO_UNID_MEDI(MEDI_DESC,MEDI_DESC_ABRE)
VALUES('PH Agua','PH');
INSERT INTO HIDRO_UNID_MEDI(MEDI_DESC,MEDI_DESC_ABRE)
VALUES('Luz UV','UV');
INSERT INTO HIDRO_UNID_MEDI(MEDI_DESC,MEDI_DESC_ABRE)
VALUES('consumo watts','watts');

INSERT INTO HIDRO_EQUI_TIPO(TIPO_DESC,TIPO_SENS_ACTU,TIPO_MEDI_CODI,TIPO_MODU_CODI)
VALUES('Temperatura','S',1,1);
INSERT INTO HIDRO_EQUI_TIPO(TIPO_DESC,TIPO_SENS_ACTU,TIPO_MEDI_CODI,TIPO_MODU_CODI)
VALUES('Humedad','S',2,2);
INSERT INTO HIDRO_EQUI_TIPO(TIPO_DESC,TIPO_SENS_ACTU,TIPO_MEDI_CODI,TIPO_MODU_CODI)
VALUES('Ambiente','S',2,2);
INSERT INTO HIDRO_EQUI_TIPO(TIPO_DESC,TIPO_SENS_ACTU,TIPO_MEDI_CODI,TIPO_MODU_CODI)
VALUES('Actuador','A',3,3);
INSERT INTO HIDRO_EQUI_TIPO(TIPO_DESC,TIPO_SENS_ACTU,TIPO_MEDI_CODI,TIPO_MODU_CODI)
VALUES('Medidor','S',4,4);

Temperatura agua
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_FOLD,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('ds18b20','temperatura agua','tanque',4,'A','28-03119779a3fa','dcaballe','dcaballe',1,1);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_FOLD,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('ds18b20','temperatura agua','semillero',4,'A','28-0319a2791dd6','dcaballe','dcaballe',1,1);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_FOLD,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('ds18b20','temperatura agua','zona1',4,'A','28-03119779ca4','dcaballe','dcaballe',1,1);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_FOLD,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('ds18b20','temperatura agua','zona2',4,'A','28-03119779ca4','dcaballe','dcaballe',1,1);

Se hace separado para traer bien los valores ya que se hace promedio de los ultimos 4:
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('dht11','humedad','north',29,'A','dcaballe','dcaballe',1,2);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('dht11','humedad','south',11,'A','dcaballe','dcaballe',1,2);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('dht11','humedad','east',13,'A','dcaballe','dcaballe',1,2);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('dht11','humedad','west',15,'A','dcaballe','dcaballe',1,2);

INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('dt11','temperatura','north',18,'A','dcaballe','dcaballe',1,3);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('dt11','temperatura','south',11,'A','dcaballe','dcaballe',1,3);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('dt11','temperatura','east',13,'A','dcaballe','dcaballe',1,3);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('dt11','temperatura','west',15,'A','dcaballe','dcaballe',1,3);


INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('rele','fan','interior',17,'A','dcaballe','dcaballe',1,3);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('rele','light','interior',23,'A','dcaballe','dcaballe',1,3);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('rele','motor','interior',24,'A','dcaballe','dcaballe',1,3);
INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('rele','sprintkler','interior',25,'A','dcaballe','dcaballe',1,3);

INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_GPIO,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('flow','flow meter','central',26,'A','dcaballe','dcaballe',1,4);

INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_PIN,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('ph','ph agua','tanque',0,'A','dcaballe','dcaballe',1,4);

INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_PIN,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('uv','luz uv','interior',1,'A','dcaballe','dcaballe',1,4);

INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_PIN,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('acs','acs llave','llave',1,'A','dcaballe','dcaballe',1,4);

INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_PIN,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('mq135','mq135 gas','interior',1,'A','dcaballe','dcaballe',1,4);

INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_PIN,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('hcsr04','tanque','interior',1,'A','dcaballe','dcaballe',1,4);

INSERT INTO HIDRO_EQUI(EQUI_MODEL,EQUI_OBSE,EQUI_UBIC,EQUI_PIN,EQUI_ESTA,EQUI_USER_REGI,EQUI_USER_MODI,EQUI_INVE_CODI,EQUI_TIPO_CODI)
VALUES('tds','tanque','interior',1,'A','dcaballe','dcaballe',1,4);

EJEMPLO TEMPERATURA AGUA
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(22,1);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(23,2);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(24,3);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(25,4);


EJEMPLO HUMEDAD
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(33,5);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(33,6);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(33,7);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(33,8);


EJEMPLO TEMPERATURA AMBIENTE
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(40,9);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(41,10);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(42,11);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(43,12);
DATOS DE PRUEBA PARA CAUDALIMETRO
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(2,17);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(3,17);
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(4,17);

DATOS DE PRUEBA PH
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(4,18);

DATOS DE PRUEBAB UV
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(4,19);

DATOS DE PRUEVA ACS
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(25,20);

DATOS DE PRUEVA MQ135
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(1,21);

Distancia hcsr04
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(1,22);

Electroconductividad
INSERT INTO HIDRO_EQUI_DETA(DETA_VALUE_LEID,DETA_EQUI_CODI)
VALUES(1,23);

TABLA CONFIGURADOR
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',1);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',2);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',3);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',4);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',5);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',6);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',7);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',8);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',9);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',10);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',11);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',12);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',13);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',14);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',15);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',16);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',18);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',19);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',20);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',21);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',22);
INSERT INTO HIDRO_EQUI_CONF (CONF_TIME_INI,CONF_TIME_FIN,CONF_DURA,CONF_ESTA,CONF_AUTO_MANU,CONF_USER_REGI,CONF_USER_MODI,CONF_EQUI_CODI)
VALUES('23:59:59','00:59:59','0.12','A','A','dcaballe','dcaballe',23);


INSERT INTO HIDRO_EQUI_ESTA (ESTA_RELE,ESTA_EQUI_CODI)
VALUES('A',13);
INSERT INTO HIDRO_EQUI_ESTA (ESTA_RELE,ESTA_EQUI_CODI)
VALUES('A',14);
INSERT INTO HIDRO_EQUI_ESTA (ESTA_RELE,ESTA_EQUI_CODI)
VALUES('A',15);
INSERT INTO HIDRO_EQUI_ESTA (ESTA_RELE,ESTA_EQUI_CODI)
VALUES('A',16);